sudo: required
services:
  - docker

before install:
  - docker build -t victorsunki/docker-nginx-react -f Dockerfile.dev .

script:
  - docker run victorsunki/docker-nginx-react npm run test -- --coverage
