sudo: required
services:
  - docker

before_install:
  - docker build -t victorsunki/docker-nginx-react -f Dockerfile.dev .

script:
  - docker run -e CI=true victorsunki/docker-nginx-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: docker-react-nginx
  env: "Dockerreactnginx-env"
  bucket_name: "elasticbeanstalk-us-east-1-398487985718"
  bucket_path: "docker-react-nginx"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
